#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

alembic upgrade head
# tail -f /dev/null
>&2 echo 'Database is available'
exec "$@" 